-- Seed remaining named trains (Podi Menike already exists in V2/V3).
-- Reuses existing stations: Polgahawela -> Polgahawela Junction (8),
-- Talawakelle -> Talawakele (17), Peradeniya -> Peradeniya (13).

INSERT INTO stations (id, name, created_at, updated_at, deleted_at) VALUES
    (27, 'Badulla', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (28, 'Dehiwala', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (29, 'Mount Lavinia', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (30, 'Moratuwa', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (31, 'Panadura', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (32, 'Kalutara', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (33, 'Aluthgama', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (34, 'Bentota', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (35, 'Ambalangoda', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (36, 'Hikkaduwa', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (37, 'Galle', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (38, 'Weligama', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (39, 'Matara', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (40, 'Beliatta', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (41, 'Kurunegala', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (42, 'Maho', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (43, 'Anuradhapura', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (44, 'Vavuniya', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (45, 'Mankulam', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (46, 'Kilinochchi', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (47, 'Jaffna', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (48, 'Kankesanthurai', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (49, 'Gal Oya', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (50, 'Valachchenai', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (51, 'Eravur', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (52, 'Batticaloa', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (53, 'Habarana', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (54, 'Kantale', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (55, 'China Bay', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (56, 'Trincomalee', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

INSERT INTO trains (id, name, created_at, updated_at, deleted_at) VALUES
    (2,  'Udarata Menike', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  'Denuwara Menike', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  'Ruhunu Kumari', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  'Galu Kumari', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  'Yal Devi', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  'Uttara Devi', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  'Udaya Devi', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  'Pulathisi', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 'Night Mail', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

INSERT INTO routes (id, departure_time, train_id, created_at, updated_at, deleted_at) VALUES
    (2,  '09:50:00', 2,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  '07:00:00', 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  '06:35:00', 4,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  '14:25:00', 5,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  '05:45:00', 6,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  '20:30:00', 7,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  '19:15:00', 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  '06:15:00', 9,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, '19:00:00', 10, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

-- Hill country (Udarata Menike, Denuwara Menike): Colombo Fort -> Badulla
INSERT INTO stop_orders (stop_sequence, route_id, station_id, created_at, updated_at, deleted_at) VALUES
    (1,  2, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  2, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  2, 4,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  2, 5,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  2, 6,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  2, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  2, 9,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  2, 13, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  2, 12, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 2, 14, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (11, 2, 15, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (12, 2, 16, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (13, 2, 17, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (14, 2, 19, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (15, 2, 23, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (16, 2, 25, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (17, 2, 26, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (18, 2, 27, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (1,  3, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  3, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  3, 4,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  3, 5,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  3, 6,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  3, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  3, 9,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  3, 13, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  3, 12, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 3, 14, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (11, 3, 15, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (12, 3, 16, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (13, 3, 17, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (14, 3, 19, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (15, 3, 23, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (16, 3, 25, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (17, 3, 26, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (18, 3, 27, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

-- Coastal: Ruhunu Kumari (Maradana -> Matara), Galu Kumari (Maradana -> Beliatta)
INSERT INTO stop_orders (stop_sequence, route_id, station_id, created_at, updated_at, deleted_at) VALUES
    (1,  4, 2,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  4, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  4, 28, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  4, 29, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  4, 30, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  4, 31, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  4, 32, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  4, 33, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  4, 34, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 4, 35, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (11, 4, 36, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (12, 4, 37, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (13, 4, 38, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (14, 4, 39, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (1,  5, 2,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  5, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  5, 28, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  5, 29, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  5, 30, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  5, 31, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  5, 32, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  5, 33, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  5, 34, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 5, 35, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (11, 5, 36, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (12, 5, 37, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (13, 5, 38, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (14, 5, 39, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (15, 5, 40, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

-- Northern: Yal Devi (via Mankulam), Uttara Devi
INSERT INTO stop_orders (stop_sequence, route_id, station_id, created_at, updated_at, deleted_at) VALUES
    (1,  6, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  6, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  6, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  6, 41, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  6, 42, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  6, 43, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  6, 44, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  6, 45, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  6, 46, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 6, 47, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (11, 6, 48, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (1,  7, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  7, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  7, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  7, 41, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  7, 42, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  7, 43, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  7, 44, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  7, 46, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  7, 47, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 7, 48, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

-- Eastern: Udaya Devi, Pulathisi, Night Mail
INSERT INTO stop_orders (stop_sequence, route_id, station_id, created_at, updated_at, deleted_at) VALUES
    (1,  8, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  8, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  8, 4,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  8, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  8, 41, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  8, 42, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  8, 49, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  8, 50, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  8, 51, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 8, 52, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (1,  9, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  9, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  9, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  9, 41, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  9, 42, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  9, 53, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  9, 49, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  9, 50, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  9, 51, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 9, 52, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (1,  10, 1,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (2,  10, 3,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (3,  10, 4,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (4,  10, 8,  CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (5,  10, 41, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (6,  10, 42, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (7,  10, 53, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (8,  10, 49, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (9,  10, 54, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (10, 10, 55, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL),
    (11, 10, 56, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL);

-- Online bookable: 1=1st, 2=2nd, 3=3rd. Coaches 4–8 offline inventory (3rd class).
INSERT INTO coaches (coach_number, train_id, class_type_id, online_bookable, created_at, updated_at, deleted_at)
SELECT
    n.n,
    t.id,
    CASE n.n WHEN 1 THEN 1 WHEN 2 THEN 2 ELSE 3 END,
    CASE WHEN n.n <= 3 THEN TRUE ELSE FALSE END,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    NULL
FROM trains t
CROSS JOIN (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8
) n
WHERE t.id BETWEEN 2 AND 10;

-- Seats: coach 1 -> 1..20; coaches 2..8 -> 1..50
INSERT INTO seats (seat_number, coach_id, created_at, updated_at, deleted_at)
WITH RECURSIVE nums AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1 FROM nums WHERE n < 50
)
SELECT n, c.id, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL
FROM nums
CROSS JOIN coaches c
WHERE c.train_id BETWEEN 2 AND 10
  AND c.coach_number = 1
  AND n <= 20
UNION ALL
SELECT n, c.id, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL
FROM nums
CROSS JOIN coaches c
WHERE c.train_id BETWEEN 2 AND 10
  AND c.coach_number BETWEEN 2 AND 8
  AND n <= 50;

-- 2nd class fares for every upstream -> downstream pair
-- hops = end_sequence - start_sequence
-- 2nd = ROUND(20.50 + (hops - 1) * hop_rate, 2)
INSERT INTO fares (price, route_id, class_type_id, start_station_id, end_station_id, created_at, updated_at, deleted_at)
SELECT
    ROUND(20.50 + (s2.stop_sequence - s1.stop_sequence - 1) * r.hop_rate, 2) AS price,
    s1.route_id,
    2 AS class_type_id,
    s1.station_id AS start_station_id,
    s2.station_id AS end_station_id,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    NULL
FROM stop_orders s1
JOIN stop_orders s2
  ON s1.route_id = s2.route_id
 AND s1.stop_sequence < s2.stop_sequence
JOIN (
    SELECT 2 AS route_id, 100.00 AS hop_rate UNION ALL
    SELECT 3, 98.50 UNION ALL
    SELECT 4, 55.00 UNION ALL
    SELECT 5, 52.00 UNION ALL
    SELECT 6, 150.00 UNION ALL
    SELECT 7, 160.00 UNION ALL
    SELECT 8, 135.00 UNION ALL
    SELECT 9, 140.00 UNION ALL
    SELECT 10, 125.00
) r ON r.route_id = s1.route_id
WHERE s1.route_id BETWEEN 2 AND 10
  AND s1.deleted_at IS NULL
  AND s2.deleted_at IS NULL;

-- 1st class = 1.5x matching 2nd-class fare
INSERT INTO fares (price, route_id, class_type_id, start_station_id, end_station_id, created_at, updated_at, deleted_at)
SELECT
    ROUND(f.price * 1.5, 2) AS price,
    f.route_id,
    1 AS class_type_id,
    f.start_station_id,
    f.end_station_id,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    NULL
FROM fares f
WHERE f.route_id BETWEEN 2 AND 10
  AND f.class_type_id = 2
  AND f.deleted_at IS NULL;

-- 3rd class = 70% of matching 2nd-class fare
INSERT INTO fares (price, route_id, class_type_id, start_station_id, end_station_id, created_at, updated_at, deleted_at)
SELECT
    ROUND(f.price * 0.70, 2) AS price,
    f.route_id,
    3 AS class_type_id,
    f.start_station_id,
    f.end_station_id,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    NULL
FROM fares f
WHERE f.route_id BETWEEN 2 AND 10
  AND f.class_type_id = 2
  AND f.deleted_at IS NULL;

ALTER TABLE stations AUTO_INCREMENT = 57;
ALTER TABLE trains AUTO_INCREMENT = 11;
ALTER TABLE routes AUTO_INCREMENT = 11;
